#!/bin/bash

hsm1="$1"
hsm2="$2"
# TODO use the token label as input instead of the slot number (as this could change for the same token across different HSMs if I'm not wrong), then look in each HSM for all the slots with that token label and operate over all of them. See https://thalesdocs.com/gphsm/ptk/5.9/docs/Content/PTK-C_Admin/Cryptoki_Config/WLD_Model/WLD_setup.htm.
slot_num="$3"
user_pin="$4"

# TODO check: is the `-d ''` really required here. Even more important: is read required here? what is its purpose?
read -r -d '' ctkmu_list_all_objects_exp <<EOF
# TODO check carefully if ctkmu could be used without interaction at all to avoid this whole expect script. Ask Thales support.
# TODO understand exactly what is going on here. This was part of the boilerplate generated by autoexpect.
set send_slow {1 .1}
proc send {ignore arg} {
    sleep .1
    exp_send -s -- \$arg
}
# TODO understand what it does.
set timeout -1
spawn ctkmu l -s $slot_num -v
expect "*Do you wish to view private \(user\) objects \\\\\[y/N]: "
send -- "y\\r"
expect "*Please enter User's PIN for the token in slot $slot_num: "
send -- "$user_pin\r"
expect eof
catch wait result
exit [lindex \$result 3]
EOF

# TODO receive a list of possibly more than 2 HSM addresses and iterate over them instead of duplicating code like below.
hsm1_output=$(ET_HSM_NETCLIENT_SERVERLIST="$hsm1" expect <<< "$ctkmu_list_all_objects_exp" 2>&1)
# TODO check: can we avoid the usage of `$?`? ShellCheck warns about it.
# TODO use bash's double-brackets instead.
if ! [ $? -eq 0 ]; then
    echo "UNKNOWN: Error listing objects from $hsm1."
    echo "$hsm1_output"
    exit 3;
fi
hsm2_output=$(ET_HSM_NETCLIENT_SERVERLIST="$hsm2" expect <<< "$ctkmu_list_all_objects_exp" 2>&1)
if ! [ $? -eq 0 ]; then
    echo "UNKNOWN: Error listing objects from $hsm2."
    echo "$hsm2_output"
    exit 3;
fi

diff_output=$(diff <(echo "$hsm1_output") <(echo "$hsm2_output"))
if [ $? -eq 0 ]; then
    echo "OK: Objects in slot $slot_num are correctly replicated.";
    exit 0;
else
    echo "CRITICAL: Objects in slot $slot_num are not correctly replicated.";
    echo "$diff_output"
    exit 2;
fi

# TODO make a comparison of the following too: ET_HSM_NETCLIENT_SERVERLIST="10.200.2.34" ctstat -a -b -j -m -s4 -v
# TODO check other attributes like total size too (totalpublicmemory?).
